export const WRITER = 'WRITER'
export const READER = 'READER'

export const QUEUE_LIMIT = 15000

/* ERRORS */
export const GENERIC_POSTGRES_CONNECTION_ERROR_MSG = new Error('ERROR_WHEN_CONNECTING_TO_POSTGRES')
export const GENERIC_POSTGRES_CONNECTION_ERROR = new Error('ERROR_WHEN_CONNECTING_TO_POSTGRES')
